# -*- coding: utf-8 -*-
"""ECT_HW5_104403553_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g9zx7yxQX1dDjHyH7S0sDmkJg1xsicKJ

## import 一些package近來
"""

import pandas as pd
import numpy as np
from sklearn import preprocessing, metrics
from sklearn.model_selection import train_test_split

df = pd.read_csv('voice.csv')
df.info()

"""## drop調空值，但是好像沒有，還是做一下
有回去看csv檔，有0值，當這個是有值
"""

df = df.dropna()
df.info()

"""## 又來encode一下，male/female這種資料要變1,0"""

label_encoder = preprocessing.LabelEncoder()
encoded_Label = label_encoder.fit_transform(df['label'])
df['label'] = encoded_Label

"""## 切一下x, y target feature"""

x=df.loc[:,["meanfreq","sd","median","Q25","Q75","IQR","skew","kurt","sp.ent","sfm","mode","centroid","meanfun","minfun","maxfun","meandom","mindom","maxdom","dfrange","modindx"]]
y=df.loc[:,['label']]

"""## 做scaling"""

scaler = preprocessing.StandardScaler()
x = scaler.fit_transform(x)

"""## 切分test 跟train"""

train_X, test_X, train_y, test_y = train_test_split(x, y, test_size = 0.33, random_state = 1)

"""## 做svm喽"""

from sklearn.svm import SVC
clf = SVC(kernel = 'linear').fit(train_X , train_y)

"""## 印出結果"""

predicted_test = clf.predict(test_X)
accuracy_test = metrics.accuracy_score(predicted_test, test_y)
print('accuracy: ',accuracy_test)

clf.score(test_X,test_y)

